### PR TITLE
Rename some things

### PR DESCRIPTION
**Pull request by sunfishcode**
`cap_primitives::std` and `cap_primitives::yanix::common::fs` were workarounds for me not being super familiar with `mod.rs` logic. 

`resolve_symlink_at` doesn't make it clear that it's just doing a single `readlink` on a single path component.

`winx::fs::get_path` avoids duplication at the callsite.

### CODE REVIEW

**Comment by sunfishcode** [comment]
Rebased and conflicts fixed, but now Windows is mysteriously failing.

**Comment by kubkon** [comment]
> Rebased and conflicts fixed, but now Windows is mysteriously failing.

Lemme provide a quick fix since I've got a Windows handy.

**Comment by sunfishcode** [comment]
I think I may have just figured it out. I was missing a `mod get_path;` after the `get_path` rename. Let's see if that fixes it.

**Comment by kubkon** [comment]
> I think I may have just figured it out. I was missing a `mod get_path;` after the `get_path` rename. Let's see if that fixes it.

Oh and actually, since it's a compile error, we could just as easily cross-verified on any OS. All it takes is to install the matching target and then run `cargo check --target x86_64-pc-windows-msvc`. I always keep forgetting that it's a possibility. ;-)

**Comment by kubkon** [comment]
@sunfishcode OK, f9590d7 should hopefully fix it!

**Comment by sunfishcode** [comment]
Indeed it does, thanks!

**Pull request merged**
